### ISSUE TITLE
scmb.py authLoginDomain= local is giving out SSL ERRORs?

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-python#144]
Here is the code https://github.com/HewlettPackard/oneview-python/blob/master/examples/scmb/scmb.py
Line 173 - 179
 <PRE>

config = {
        "ip": args.host,
        "credentials": {
            "userName": args.user,
            "password": args.passwd
        }
    }
</PRE>
is substituted with
<PRE>
 config = {
        "ip": args.host,
        "credentials": {
            "userName": args.user,
            "password": args.passwd,
            "authLoginDomain": 'local'
        }

</PRE>

<PRE>
python scmb.work.py -a 19.14.XXX.XXX -u administrator -p XXXXXX -d
python scmb.work.py -a 19.14.XX.XX  -u administrator -p XXXXXX 
>> python scmb.work.py -a 19.XX.XX.XX -u administrator -p 'XXXXXXX'
Traceback (most recent call last):
  File "scmb.work.py", line 186, in <module>
    sys.exit(main())
  File "scmb.work.py", line 179, in main
    recv(args.host, args.route)
  File "scmb.work.py", line 81, in recv
    conn.connect()
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/amqp/connection.py", line 323, in connect
    self.transport.connect()
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/amqp/transport.py", line 115, in connect
    self.socket_settings, self.read_timeout, self.write_timeout,
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/amqp/transport.py", line 225, in _init_socket
    self._setup_transport()
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/amqp/transport.py", line 405, in _setup_transport
    self.sock.do_handshake()
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

> pip freeze |grep amqp
amqp==5.0.5
</PRE>

**Comment by nabhajit-ray** [comment]
Thanks Zeshan for raising this. We will be looking into this.

**Comment by SHANDCRUZ** [comment]
Hi @zeshan1977 we have made a fix to scmb code and merged into the master branch. Let us know if you are still facing any issue. Please pull the latest master and retry the scmb script. Also feel free to reopen if the issue still exists.
