### ISSUE TITLE
TypeError: get_all() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by navisidhu** [HewlettPackard/oneview-python#71]
# Info
Python Version : 3.8.2
OS: Fedora 32 (Workstation Edition)

# Bug Description
When trying to use the SDK directly, we encountered the issue with the `get_by_name` function on the `Resource` object.

# Test Script
```
#!/usr/bin/env python

import argparse
import getpass
from hpOneView.oneview_client import OneViewClient


def main(args):
    config = dict(ip=args.server, api_version=1600, credentials=dict(userName=args.username, password=args.password))
    client = OneViewClient(config)
    scope = client.scopes.get_by_name('PreProd')
    if scope:
        print("Scope already exists.")
    else:
        scope = client.scopes.create(data=dict(name="PreProd"))
        print("Created new scope")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Create Scope in OneView')
    parser.add_argument('-s', '--server', required=True, help='OneView Endpoint')
    parser.add_argument('-u', '--username', required=True, help='Device Username')
    parser.add_argument('-p', '--password', help='Device Password')
    args = parser.parse_args()
    if args.password is None:
        args.password = getpass.getpass("Password: ")
    main(args)
```

# Output
```
Password: 
Traceback (most recent call last):
  File "createscope.py", line 27, in <module>
    main(args)
  File "createscope.py", line 11, in main
    scope = client.scopes.get_by_name('PreProd')
  File "/home/nsidhu/.local/lib/python3.8/site-packages/hpOneView/resources/resource.py", line 261, in get_by_name
    result = self.get_by("name", name)
  File "/home/nsidhu/.local/lib/python3.8/site-packages/hpOneView/resources/resource.py", line 244, in get_by
    results = self.get_all(filter=filter)
TypeError: get_all() got an unexpected keyword argument 'filter'
```

**Comment by navisidhu** [comment]
I've tested the script against version `5.2.0` and `5.2.1` on Python versions `2.7.3` and `3.8.2` and get the same error.

**Comment by chebroluharika** [comment]
Hi @navisidhu,
Thanks for pointing this out. Please try running script with version: 5.3.0 as we had fixed this issue in latest release.

**Comment by VenkateshRavula** [comment]
@navisidhu , Also please refer to example file for info on usage.
https://github.com/HewlettPackard/oneview-python/blob/master/examples/scopes.py
